// Code generated by entc, DO NOT EDIT.

package task

import (
	"time"

	"github.com/minskylab/asclepius/ent/schema"
)

const (
	// Label holds the string label denoting the task type in the database.
	Label = "task"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTitle holds the string denoting the title vertex property in the database.
	FieldTitle = "title"
	// FieldStartAt holds the string denoting the startat vertex property in the database.
	FieldStartAt = "start_at"
	// FieldEndsAt holds the string denoting the endsat vertex property in the database.
	FieldEndsAt = "ends_at"
	// FieldDescription holds the string denoting the description vertex property in the database.
	FieldDescription = "description"

	// Table holds the table name of the task in the database.
	Table = "tasks"
	// ResponsibleTable is the table the holds the responsible relation/edge.
	ResponsibleTable = "medicus"
	// ResponsibleInverseTable is the table name for the Medicus entity.
	// It exists in this package in order to avoid circular dependency with the "medicus" package.
	ResponsibleInverseTable = "medicus"
	// ResponsibleColumn is the table column denoting the responsible relation/edge.
	ResponsibleColumn = "task_responsible"
	// ScheduleTable is the table the holds the schedule relation/edge.
	ScheduleTable = "tasks"
	// ScheduleInverseTable is the table name for the Schedule entity.
	// It exists in this package in order to avoid circular dependency with the "schedule" package.
	ScheduleInverseTable = "schedules"
	// ScheduleColumn is the table column denoting the schedule relation/edge.
	ScheduleColumn = "schedule_tasks"
)

// Columns holds all SQL columns for task fields.
var Columns = []string{
	FieldID,
	FieldTitle,
	FieldStartAt,
	FieldEndsAt,
	FieldDescription,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Task type.
var ForeignKeys = []string{
	"schedule_tasks",
}

var (
	fields = schema.Task{}.Fields()

	// descStartAt is the schema descriptor for startAt field.
	descStartAt = fields[2].Descriptor()
	// DefaultStartAt holds the default value on creation for the startAt field.
	DefaultStartAt = descStartAt.Default.(func() time.Time)

	// descEndsAt is the schema descriptor for endsAt field.
	descEndsAt = fields[3].Descriptor()
	// DefaultEndsAt holds the default value on creation for the endsAt field.
	DefaultEndsAt = descEndsAt.Default.(func() time.Time)
)
