// Code generated by entc, DO NOT EDIT.

package history

const (
	// Label holds the string label denoting the history type in the database.
	Label = "history"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the history in the database.
	Table = "histories"
	// PatientTable is the table the holds the patient relation/edge.
	PatientTable = "histories"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_history"
	// TestsTable is the table the holds the tests relation/edge.
	TestsTable = "tests"
	// TestsInverseTable is the table name for the Test entity.
	// It exists in this package in order to avoid circular dependency with the "test" package.
	TestsInverseTable = "tests"
	// TestsColumn is the table column denoting the tests relation/edge.
	TestsColumn = "history_tests"
	// NotesTable is the table the holds the notes relation/edge.
	NotesTable = "medical_notes"
	// NotesInverseTable is the table name for the MedicalNote entity.
	// It exists in this package in order to avoid circular dependency with the "medicalnote" package.
	NotesInverseTable = "medical_notes"
	// NotesColumn is the table column denoting the notes relation/edge.
	NotesColumn = "history_notes"
)

// Columns holds all SQL columns for history fields.
var Columns = []string{
	FieldID,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the History type.
var ForeignKeys = []string{
	"patient_history",
}
