// Code generated by entc, DO NOT EDIT.

package doctor

import (
	"fmt"
	"time"

	"github.com/minskylab/asclepius/ent/schema"
)

const (
	// Label holds the string label denoting the doctor type in the database.
	Label = "doctor"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name vertex property in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email vertex property in the database.
	FieldEmail = "email"
	// FieldPhone holds the string denoting the phone vertex property in the database.
	FieldPhone = "phone"
	// FieldState holds the string denoting the state vertex property in the database.
	FieldState = "state"
	// FieldLastConnection holds the string denoting the lastconnection vertex property in the database.
	FieldLastConnection = "last_connection"
	// FieldVolunteer holds the string denoting the volunteer vertex property in the database.
	FieldVolunteer = "volunteer"

	// Table holds the table name of the doctor in the database.
	Table = "doctors"
	// NotesTable is the table the holds the notes relation/edge.
	NotesTable = "medical_notes"
	// NotesInverseTable is the table name for the MedicalNote entity.
	// It exists in this package in order to avoid circular dependency with the "medicalnote" package.
	NotesInverseTable = "medical_notes"
	// NotesColumn is the table column denoting the notes relation/edge.
	NotesColumn = "doctor_notes"
	// TasksTable is the table the holds the tasks relation/edge. The primary key declared below.
	TasksTable = "task_responsible"
	// TasksInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TasksInverseTable = "tasks"
)

// Columns holds all SQL columns for doctor fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldPhone,
	FieldState,
	FieldLastConnection,
	FieldVolunteer,
}

var (
	// TasksPrimaryKey and TasksColumn2 are the table columns denoting the
	// primary key for the tasks relation (M2M).
	TasksPrimaryKey = []string{"task_id", "doctor_id"}
)

var (
	fields = schema.Doctor{}.Fields()

	// descLastConnection is the schema descriptor for lastConnection field.
	descLastConnection = fields[5].Descriptor()
	// DefaultLastConnection holds the default value on creation for the lastConnection field.
	DefaultLastConnection = descLastConnection.Default.(func() time.Time)

	// descVolunteer is the schema descriptor for volunteer field.
	descVolunteer = fields[6].Descriptor()
	// DefaultVolunteer holds the default value on creation for the volunteer field.
	DefaultVolunteer = descVolunteer.Default.(bool)
)

// State defines the type for the state enum field.
type State string

// State values.
const (
	StateIdle        State = "idle"
	StateWorking     State = "working"
	StateUnavailable State = "unavailable"
)

func (s State) String() string {
	return string(s)
}

// StateValidator is a validator for the "s" field enum values. It is called by the builders before save.
func StateValidator(s State) error {
	switch s {
	case StateIdle, StateWorking, StateUnavailable:
		return nil
	default:
		return fmt.Errorf("doctor: invalid enum value for state field: %q", s)
	}
}
