// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/google/uuid"
	"github.com/minskylab/asclepius/ent/doctor"
	"github.com/minskylab/asclepius/ent/medicalnote"
	"github.com/minskylab/asclepius/ent/task"
)

// DoctorCreate is the builder for creating a Doctor entity.
type DoctorCreate struct {
	config
	id             *uuid.UUID
	name           *[]string
	email          *string
	phone          *string
	state          *doctor.State
	lastConnection *time.Time
	volunteer      *bool
	notes          map[uuid.UUID]struct{}
	tasks          map[uuid.UUID]struct{}
}

// SetName sets the name field.
func (dc *DoctorCreate) SetName(s []string) *DoctorCreate {
	dc.name = &s
	return dc
}

// SetEmail sets the email field.
func (dc *DoctorCreate) SetEmail(s string) *DoctorCreate {
	dc.email = &s
	return dc
}

// SetPhone sets the phone field.
func (dc *DoctorCreate) SetPhone(s string) *DoctorCreate {
	dc.phone = &s
	return dc
}

// SetState sets the state field.
func (dc *DoctorCreate) SetState(d doctor.State) *DoctorCreate {
	dc.state = &d
	return dc
}

// SetLastConnection sets the lastConnection field.
func (dc *DoctorCreate) SetLastConnection(t time.Time) *DoctorCreate {
	dc.lastConnection = &t
	return dc
}

// SetNillableLastConnection sets the lastConnection field if the given value is not nil.
func (dc *DoctorCreate) SetNillableLastConnection(t *time.Time) *DoctorCreate {
	if t != nil {
		dc.SetLastConnection(*t)
	}
	return dc
}

// SetVolunteer sets the volunteer field.
func (dc *DoctorCreate) SetVolunteer(b bool) *DoctorCreate {
	dc.volunteer = &b
	return dc
}

// SetNillableVolunteer sets the volunteer field if the given value is not nil.
func (dc *DoctorCreate) SetNillableVolunteer(b *bool) *DoctorCreate {
	if b != nil {
		dc.SetVolunteer(*b)
	}
	return dc
}

// SetID sets the id field.
func (dc *DoctorCreate) SetID(u uuid.UUID) *DoctorCreate {
	dc.id = &u
	return dc
}

// AddNoteIDs adds the notes edge to MedicalNote by ids.
func (dc *DoctorCreate) AddNoteIDs(ids ...uuid.UUID) *DoctorCreate {
	if dc.notes == nil {
		dc.notes = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		dc.notes[ids[i]] = struct{}{}
	}
	return dc
}

// AddNotes adds the notes edges to MedicalNote.
func (dc *DoctorCreate) AddNotes(m ...*MedicalNote) *DoctorCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return dc.AddNoteIDs(ids...)
}

// AddTaskIDs adds the tasks edge to Task by ids.
func (dc *DoctorCreate) AddTaskIDs(ids ...uuid.UUID) *DoctorCreate {
	if dc.tasks == nil {
		dc.tasks = make(map[uuid.UUID]struct{})
	}
	for i := range ids {
		dc.tasks[ids[i]] = struct{}{}
	}
	return dc
}

// AddTasks adds the tasks edges to Task.
func (dc *DoctorCreate) AddTasks(t ...*Task) *DoctorCreate {
	ids := make([]uuid.UUID, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return dc.AddTaskIDs(ids...)
}

// Save creates the Doctor in the database.
func (dc *DoctorCreate) Save(ctx context.Context) (*Doctor, error) {
	if dc.name == nil {
		return nil, errors.New("ent: missing required field \"name\"")
	}
	if dc.email == nil {
		return nil, errors.New("ent: missing required field \"email\"")
	}
	if dc.phone == nil {
		return nil, errors.New("ent: missing required field \"phone\"")
	}
	if dc.state == nil {
		return nil, errors.New("ent: missing required field \"state\"")
	}
	if err := doctor.StateValidator(*dc.state); err != nil {
		return nil, fmt.Errorf("ent: validator failed for field \"state\": %v", err)
	}
	if dc.lastConnection == nil {
		v := doctor.DefaultLastConnection()
		dc.lastConnection = &v
	}
	if dc.volunteer == nil {
		v := doctor.DefaultVolunteer
		dc.volunteer = &v
	}
	return dc.sqlSave(ctx)
}

// SaveX calls Save and panics if Save returns an error.
func (dc *DoctorCreate) SaveX(ctx context.Context) *Doctor {
	v, err := dc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (dc *DoctorCreate) sqlSave(ctx context.Context) (*Doctor, error) {
	var (
		d     = &Doctor{config: dc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: doctor.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: doctor.FieldID,
			},
		}
	)
	if value := dc.id; value != nil {
		d.ID = *value
		_spec.ID.Value = *value
	}
	if value := dc.name; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  *value,
			Column: doctor.FieldName,
		})
		d.Name = *value
	}
	if value := dc.email; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: doctor.FieldEmail,
		})
		d.Email = *value
	}
	if value := dc.phone; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  *value,
			Column: doctor.FieldPhone,
		})
		d.Phone = *value
	}
	if value := dc.state; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  *value,
			Column: doctor.FieldState,
		})
		d.State = *value
	}
	if value := dc.lastConnection; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  *value,
			Column: doctor.FieldLastConnection,
		})
		d.LastConnection = *value
	}
	if value := dc.volunteer; value != nil {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  *value,
			Column: doctor.FieldVolunteer,
		})
		d.Volunteer = *value
	}
	if nodes := dc.notes; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   doctor.NotesTable,
			Columns: []string{doctor.NotesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: medicalnote.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := dc.tasks; len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   doctor.TasksTable,
			Columns: doctor.TasksPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: task.FieldID,
				},
			},
		}
		for k, _ := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if err := sqlgraph.CreateNode(ctx, dc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return d, nil
}
