// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/minskylab/asclepius/ent/medicalnote"
	"github.com/minskylab/asclepius/ent/predicate"
)

// MedicalNoteDelete is the builder for deleting a MedicalNote entity.
type MedicalNoteDelete struct {
	config
	predicates []predicate.MedicalNote
}

// Where adds a new predicate to the delete builder.
func (mnd *MedicalNoteDelete) Where(ps ...predicate.MedicalNote) *MedicalNoteDelete {
	mnd.predicates = append(mnd.predicates, ps...)
	return mnd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mnd *MedicalNoteDelete) Exec(ctx context.Context) (int, error) {
	return mnd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (mnd *MedicalNoteDelete) ExecX(ctx context.Context) int {
	n, err := mnd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mnd *MedicalNoteDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: medicalnote.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: medicalnote.FieldID,
			},
		},
	}
	if ps := mnd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, mnd.driver, _spec)
}

// MedicalNoteDeleteOne is the builder for deleting a single MedicalNote entity.
type MedicalNoteDeleteOne struct {
	mnd *MedicalNoteDelete
}

// Exec executes the deletion query.
func (mndo *MedicalNoteDeleteOne) Exec(ctx context.Context) error {
	n, err := mndo.mnd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{medicalnote.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mndo *MedicalNoteDeleteOne) ExecX(ctx context.Context) {
	mndo.mnd.ExecX(ctx)
}
