// Code generated by entc, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/minskylab/asclepius/ent/medicus"
)

// Medicus is the model entity for the Medicus schema.
type Medicus struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name []string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// State holds the value of the "state" field.
	State medicus.State `json:"state,omitempty"`
	// LastConnection holds the value of the "lastConnection" field.
	LastConnection time.Time `json:"lastConnection,omitempty"`
	// Volunteer holds the value of the "volunteer" field.
	Volunteer bool `json:"volunteer,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MedicusQuery when eager-loading is set.
	Edges            MedicusEdges `json:"edges"`
	task_responsible *uuid.UUID
}

// MedicusEdges holds the relations/edges for other nodes in the graph.
type MedicusEdges struct {
	// Notes holds the value of the notes edge.
	Notes []*MedicalNote
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// NotesOrErr returns the Notes value or an error if the edge
// was not loaded in eager-loading.
func (e MedicusEdges) NotesOrErr() ([]*MedicalNote, error) {
	if e.loadedTypes[0] {
		return e.Notes, nil
	}
	return nil, &NotLoadedError{edge: "notes"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Medicus) scanValues() []interface{} {
	return []interface{}{
		&uuid.UUID{},      // id
		&[]byte{},         // name
		&sql.NullString{}, // email
		&sql.NullString{}, // phone
		&sql.NullString{}, // state
		&sql.NullTime{},   // lastConnection
		&sql.NullBool{},   // volunteer
	}
}

// fkValues returns the types for scanning foreign-keys values from sql.Rows.
func (*Medicus) fkValues() []interface{} {
	return []interface{}{
		&uuid.UUID{}, // task_responsible
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Medicus fields.
func (m *Medicus) assignValues(values ...interface{}) error {
	if m, n := len(values), len(medicus.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	if value, ok := values[0].(*uuid.UUID); !ok {
		return fmt.Errorf("unexpected type %T for field id", values[0])
	} else if value != nil {
		m.ID = *value
	}
	values = values[1:]

	if value, ok := values[0].(*[]byte); !ok {
		return fmt.Errorf("unexpected type %T for field name", values[0])
	} else if value != nil && len(*value) > 0 {
		if err := json.Unmarshal(*value, &m.Name); err != nil {
			return fmt.Errorf("unmarshal field name: %v", err)
		}
	}
	if value, ok := values[1].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field email", values[1])
	} else if value.Valid {
		m.Email = value.String
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field phone", values[2])
	} else if value.Valid {
		m.Phone = value.String
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field state", values[3])
	} else if value.Valid {
		m.State = medicus.State(value.String)
	}
	if value, ok := values[4].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field lastConnection", values[4])
	} else if value.Valid {
		m.LastConnection = value.Time
	}
	if value, ok := values[5].(*sql.NullBool); !ok {
		return fmt.Errorf("unexpected type %T for field volunteer", values[5])
	} else if value.Valid {
		m.Volunteer = value.Bool
	}
	values = values[6:]
	if len(values) == len(medicus.ForeignKeys) {
		if value, ok := values[0].(*uuid.UUID); !ok {
			return fmt.Errorf("unexpected type %T for field task_responsible", values[0])
		} else if value != nil {
			m.task_responsible = value
		}
	}
	return nil
}

// QueryNotes queries the notes edge of the Medicus.
func (m *Medicus) QueryNotes() *MedicalNoteQuery {
	return (&MedicusClient{config: m.config}).QueryNotes(m)
}

// Update returns a builder for updating this Medicus.
// Note that, you need to call Medicus.Unwrap() before calling this method, if this Medicus
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Medicus) Update() *MedicusUpdateOne {
	return (&MedicusClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (m *Medicus) Unwrap() *Medicus {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Medicus is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Medicus) String() string {
	var builder strings.Builder
	builder.WriteString("Medicus(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteString(", name=")
	builder.WriteString(fmt.Sprintf("%v", m.Name))
	builder.WriteString(", email=")
	builder.WriteString(m.Email)
	builder.WriteString(", phone=")
	builder.WriteString(m.Phone)
	builder.WriteString(", state=")
	builder.WriteString(fmt.Sprintf("%v", m.State))
	builder.WriteString(", lastConnection=")
	builder.WriteString(m.LastConnection.Format(time.ANSIC))
	builder.WriteString(", volunteer=")
	builder.WriteString(fmt.Sprintf("%v", m.Volunteer))
	builder.WriteByte(')')
	return builder.String()
}

// MedicusSlice is a parsable slice of Medicus.
type MedicusSlice []*Medicus

func (m MedicusSlice) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
