// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
	"github.com/minskylab/asclepius/ent/predicate"
	"github.com/minskylab/asclepius/ent/taskresponse"
)

// TaskResponseDelete is the builder for deleting a TaskResponse entity.
type TaskResponseDelete struct {
	config
	predicates []predicate.TaskResponse
}

// Where adds a new predicate to the delete builder.
func (trd *TaskResponseDelete) Where(ps ...predicate.TaskResponse) *TaskResponseDelete {
	trd.predicates = append(trd.predicates, ps...)
	return trd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (trd *TaskResponseDelete) Exec(ctx context.Context) (int, error) {
	return trd.sqlExec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (trd *TaskResponseDelete) ExecX(ctx context.Context) int {
	n, err := trd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (trd *TaskResponseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: taskresponse.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: taskresponse.FieldID,
			},
		},
	}
	if ps := trd.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, trd.driver, _spec)
}

// TaskResponseDeleteOne is the builder for deleting a single TaskResponse entity.
type TaskResponseDeleteOne struct {
	trd *TaskResponseDelete
}

// Exec executes the deletion query.
func (trdo *TaskResponseDeleteOne) Exec(ctx context.Context) error {
	n, err := trdo.trd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{taskresponse.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (trdo *TaskResponseDeleteOne) ExecX(ctx context.Context) {
	trdo.trd.ExecX(ctx)
}
