// Code generated by entc, DO NOT EDIT.

package test

const (
	// Label holds the string label denoting the test type in the database.
	Label = "test"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNotes holds the string denoting the notes vertex property in the database.
	FieldNotes = "notes"

	// Table holds the table name of the test in the database.
	Table = "tests"
	// HistoryTable is the table the holds the history relation/edge.
	HistoryTable = "tests"
	// HistoryInverseTable is the table name for the History entity.
	// It exists in this package in order to avoid circular dependency with the "history" package.
	HistoryInverseTable = "histories"
	// HistoryColumn is the table column denoting the history relation/edge.
	HistoryColumn = "history_tests"
	// ClinicalTable is the table the holds the clinical relation/edge.
	ClinicalTable = "clinical_results"
	// ClinicalInverseTable is the table name for the ClinicalResults entity.
	// It exists in this package in order to avoid circular dependency with the "clinicalresults" package.
	ClinicalInverseTable = "clinical_results"
	// ClinicalColumn is the table column denoting the clinical relation/edge.
	ClinicalColumn = "test_clinical"
	// EpidemiologicTable is the table the holds the epidemiologic relation/edge.
	EpidemiologicTable = "epidemiologic_results"
	// EpidemiologicInverseTable is the table name for the EpidemiologicResults entity.
	// It exists in this package in order to avoid circular dependency with the "epidemiologicresults" package.
	EpidemiologicInverseTable = "epidemiologic_results"
	// EpidemiologicColumn is the table column denoting the epidemiologic relation/edge.
	EpidemiologicColumn = "test_epidemiologic"
)

// Columns holds all SQL columns for test fields.
var Columns = []string{
	FieldID,
	FieldNotes,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Test type.
var ForeignKeys = []string{
	"history_tests",
}
