// Code generated by entc, DO NOT EDIT.

package alert

const (
	// Label holds the string label denoting the alert type in the database.
	Label = "alert"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"

	// Table holds the table name of the alert in the database.
	Table = "alerts"
)

// Columns holds all SQL columns for alert fields.
var Columns = []string{
	FieldID,
}
