// Code generated by entc, DO NOT EDIT.

package taskresponse

import (
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/minskylab/asclepius/ent/predicate"
)

// ID filters vertices based on their identifier.
func ID(id uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// At applies equality check predicate on the "at" field. It's identical to AtEQ.
func At(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAt), v))
	})
}

// LastChange applies equality check predicate on the "lastChange" field. It's identical to LastChangeEQ.
func LastChange(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLastChange), v))
	})
}

// AtEQ applies the EQ predicate on the "at" field.
func AtEQ(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldAt), v))
	})
}

// AtNEQ applies the NEQ predicate on the "at" field.
func AtNEQ(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldAt), v))
	})
}

// AtIn applies the In predicate on the "at" field.
func AtIn(vs ...time.Time) predicate.TaskResponse {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskResponse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldAt), v...))
	})
}

// AtNotIn applies the NotIn predicate on the "at" field.
func AtNotIn(vs ...time.Time) predicate.TaskResponse {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskResponse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldAt), v...))
	})
}

// AtGT applies the GT predicate on the "at" field.
func AtGT(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldAt), v))
	})
}

// AtGTE applies the GTE predicate on the "at" field.
func AtGTE(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldAt), v))
	})
}

// AtLT applies the LT predicate on the "at" field.
func AtLT(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldAt), v))
	})
}

// AtLTE applies the LTE predicate on the "at" field.
func AtLTE(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldAt), v))
	})
}

// LastChangeEQ applies the EQ predicate on the "lastChange" field.
func LastChangeEQ(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldLastChange), v))
	})
}

// LastChangeNEQ applies the NEQ predicate on the "lastChange" field.
func LastChangeNEQ(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldLastChange), v))
	})
}

// LastChangeIn applies the In predicate on the "lastChange" field.
func LastChangeIn(vs ...time.Time) predicate.TaskResponse {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskResponse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldLastChange), v...))
	})
}

// LastChangeNotIn applies the NotIn predicate on the "lastChange" field.
func LastChangeNotIn(vs ...time.Time) predicate.TaskResponse {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.TaskResponse(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(vs) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldLastChange), v...))
	})
}

// LastChangeGT applies the GT predicate on the "lastChange" field.
func LastChangeGT(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldLastChange), v))
	})
}

// LastChangeGTE applies the GTE predicate on the "lastChange" field.
func LastChangeGTE(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldLastChange), v))
	})
}

// LastChangeLT applies the LT predicate on the "lastChange" field.
func LastChangeLT(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldLastChange), v))
	})
}

// LastChangeLTE applies the LTE predicate on the "lastChange" field.
func LastChangeLTE(v time.Time) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldLastChange), v))
	})
}

// MetaIsNil applies the IsNil predicate on the "meta" field.
func MetaIsNil() predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldMeta)))
	})
}

// MetaNotNil applies the NotNil predicate on the "meta" field.
func MetaNotNil() predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldMeta)))
	})
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AuthorTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.Doctor) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(AuthorInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTask applies the HasEdge predicate on the "task" edge.
func HasTask() predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TaskTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTaskWith applies the HasEdge predicate on the "task" edge with a given conditions (other predicates).
func HasTaskWith(preds ...predicate.Task) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TaskInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups list of predicates with the AND operator between them.
func And(predicates ...predicate.TaskResponse) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups list of predicates with the OR operator between them.
func Or(predicates ...predicate.TaskResponse) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TaskResponse) predicate.TaskResponse {
	return predicate.TaskResponse(func(s *sql.Selector) {
		p(s.Not())
	})
}
