// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Alert is the predicate function for alert builders.
type Alert func(*sql.Selector)

// ClinicalResults is the predicate function for clinicalresults builders.
type ClinicalResults func(*sql.Selector)

// Doctor is the predicate function for doctor builders.
type Doctor func(*sql.Selector)

// EpidemiologicResults is the predicate function for epidemiologicresults builders.
type EpidemiologicResults func(*sql.Selector)

// History is the predicate function for history builders.
type History func(*sql.Selector)

// MedicalNote is the predicate function for medicalnote builders.
type MedicalNote func(*sql.Selector)

// Patient is the predicate function for patient builders.
type Patient func(*sql.Selector)

// Schedule is the predicate function for schedule builders.
type Schedule func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TaskResponse is the predicate function for taskresponse builders.
type TaskResponse func(*sql.Selector)

// Test is the predicate function for test builders.
type Test func(*sql.Selector)
